# Generated by Django 4.1.1 on 2022-10-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
