# Generated by Django 4.1.3 on 2022-11-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Названия автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='CarMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Названия марки автомобиля')),
                ('Firms', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.firms')),
            ],
        ),
    ]
