# Generated by Django 4.1.3 on 2022-11-20 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmarks',
            old_name='Firms',
            new_name='firms',
        ),
    ]
