# Generated by Django 4.1.3 on 2022-11-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='auth_user',
            new_name='auth_user_id',
        ),
    ]
