# Generated by Django 4.1.3 on 2022-11-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_firms_carmarks_firms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firms',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Названия фирмы автомобиля'),
        ),
    ]
