# Generated by Django 4.1.3 on 2022-11-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_auth_user_orders_auth_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='auth_user_id',
            new_name='auth_user',
        ),
    ]
