# Generated by Django 4.1.3 on 2022-11-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_firms_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmarks',
            options={'verbose_name': 'Марка автомобиля', 'verbose_name_plural': 'Марки автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='firms',
            options={'verbose_name': 'Фирма автомобиля', 'verbose_name_plural': 'Фирмы автомобилей'},
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=15, verbose_name='Названия номера автомобиля')),
                ('carmarks', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.carmarks')),
            ],
            options={
                'verbose_name': 'Номер автомобиля',
                'verbose_name_plural': 'Номера автомобилей',
            },
        ),
    ]
