# Generated by Django 4.1.3 on 2022-11-30 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_marks_alter_cars_options_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marks',
            options={'managed': False, 'verbose_name': 'Модель автомобиля', 'verbose_name_plural': 'Модели автомобилей'},
        ),
    ]
