# Generated by Django 4.1.3 on 2022-11-30 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_marks_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marks',
            options={'managed': False, 'verbose_name': 'Модель автомобиля', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelTable(
            name='marks',
            table='records',
        ),
    ]
