# Generated by Django 4.1.3 on 2022-11-30 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_marks_options_alter_marks_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marks',
            table='marks',
        ),
    ]
