# Generated by Django 4.1.3 on 2022-11-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_name_carmarks_name_car_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='carmarks',
        ),
        migrations.AddField(
            model_name='cars',
            name='firms',
            field=models.CharField(default='', max_length=15, verbose_name='Фирма автомобиля'),
        ),
        migrations.AddField(
            model_name='cars',
            name='mark',
            field=models.CharField(default='', max_length=15, verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_number',
            field=models.CharField(default='', max_length=15, verbose_name='Номера автомобиля'),
        ),
        migrations.DeleteModel(
            name='CarMarks',
        ),
        migrations.DeleteModel(
            name='Firms',
        ),
    ]
