# Generated by Django 4.1.3 on 2022-11-30 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_marks_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': 'автомобиль', 'verbose_name_plural': 'Список автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='records',
            options={'verbose_name': 'запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
