# Generated by Django 4.1.3 on 2022-11-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cars',
            table='cars',
        ),
    ]
