# Generated by Django 4.1.3 on 2022-11-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cars_options_alter_records_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'managed': False, 'verbose_name': 'автомобиль', 'verbose_name_plural': 'Список автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='records',
            options={'managed': False, 'verbose_name': 'запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
