# Generated by Django 4.1.3 on 2022-12-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cars_options_alter_records_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
