# Generated by Django 4.1.3 on 2022-11-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cars_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={},
        ),
    ]
